[Refactor] #232 Service Layer 분리 (Reply, Feed, Notification)
FoodieLog/foodie-log-server pull request #234
Opened 2024-02-27 06:49 UTC by sohn919

## 요약
- Reply, Feed, Notification Service Layer 분리

## 작업 내용
- Sevice Layer 분리

## 참고 사항
- Service Layer 를 분리하면서 report, media, follow, feedLike 추가 패키지 생성 (moduleService)
- moduleService 가 예외 처리도 같이 하면서 Service 가 비지니스 로직만 담당하게 하려고 추가로 만들었는데 dao 역할을 그대로 하는 경우들이 보입니다. 이번주 테스트 코드를 작성하면서 코드 정리를 해야 할 듯 싶네요!
- 현재 남은 곳은 restaurant 로 확인됩니다.

## 관련 이슈
#232

2024-02-27 07:13 UTC, chaewon12 requested changes
전체적으로 모듈 서비스 네이밍이 JPA 쿼리메서드 네이밍 복붙인 것 같습니다. 
적절하게 수정해주실 수 있을까요

그리고 [dao 역할을 그대로 하는 경우] 저도 발견했는데 나중에 어떤 예외 처리가 추가 될지 모르고 
그런 경우를 생각하면 걱정하지 않아도 될 부분인 것 같습니다. 

추후 만약 JPQL로 변환한다면  repository.method() 이렇게 단순 호출로만 보이는
의미없어 보이는  모듈들의 어색함도 사라질 듯 하네요

2024-02-27 07:13 UTC, chaewon12 commented on application/src/main/java/com/foodielog/application/feed/service/FeedModuleService.java
> +		LocalDateTime now = LocalDateTime.now();
List 반환이니까 네이밍도 반영해주세요 
Feeds or FeedList 
저는 Feeds로 했습니다.

2024-02-27 07:13 UTC, chaewon12 commented on application/src/main/java/com/foodielog/application/feed/service/FeedService.java
> +        if (restaurantLikeModuleService.existsByUserAndRestaurant(user, restaurant)) {
네이밍이 너무 Repository 스럽습니다...
by~ 이부분 전달 파라미터 정보로도 충분히 알 수 있지 않나용

2024-02-27 07:13 UTC, chaewon12 commented on application/src/main/java/com/foodielog/application/feed/service/FeedService.java
> +                restaurantModuleService.getRestaurantByPlaceId(restaurant.getKakaoPlaceId());
여기도요

2024-02-27 08:12 UTC, sohn919 commented on application/src/main/java/com/foodielog/application/feed/service/FeedModuleService.java
> +		LocalDateTime now = LocalDateTime.now();
네이밍 반영 확인했습니다. 안그래도 하면서 repo 네이밍이랑 같아서 이게 dao 인가 싶은 느낌이 굉장히 들었습니다.
밑에 리뷰도 반영하겠습니다!

2024-02-28 08:07 UTC, sohn919 commented
RestaurantService 부분 추가로 작업해서 올렸습니다!
- 네이밍에 대한 부분은 수정은 했는데 3가지 형태로 나누어 지는 부분은 어떻게 네이밍을 할지 생각이 안나서 밑에 형태로 진행했습니다.
```java
public Optional<Restaurant> getByPlaceId(String placeId) {
        return restaurantRepository.findByKakaoPlaceId(placeId);
    }

    public List<Restaurant> getByAddress(String address) {
        return restaurantRepository.findByRoadAddressContaining(address);
    }

    public Restaurant getById(Long id) {
        return restaurantRepository.findById(id)
                .orElseThrow(() -> new Exception404("식당을 찾을 수 없습니다."));
    }
```

2024-02-28 08:50 UTC, chaewon12 commented
쿼리 조건에 따라 메서드의 이름을 다르게 하기보단  
메서드 명에는 행위만 적고 조건은 매개변수 두는게 
가독성 측면에서도 그렇고 유지보수성 측면에서도 좋을 것 같습니다. 
(새로운 기능을 추가하거나 기존 기능을 변경할 때 메서드 이름도 함께 변경해야 할 가능성이 높아질 수 있음)

메서드 시그니쳐가 다르면 메서드 명은 동일해도 상관 없기 때문에 (=> 메서드 오버로딩)
getOptionalRestaurant / getRestaurant / getRestaurants
이런식으로 [get+받으려는 데이터] 형식으로 하는건 어떨까요

2024-03-13 12:17 UTC, sohn919 commented
채원님이 남기신 코멘트대로 메서드 명 진행했습니다.

2024-03-13 13:31 UTC, chaewon12 approved these changes

2024-03-13 13:31 UTC, merged